# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookkyProject-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookkyProject-iOS
  pod 'Alamofire'
  pod 'Cosmos', '~> 23.0'
  target 'BookkyProject-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookkyProject-iOSUITests' do
    # Pods for testing
  end

end
